### ISSUE TITLE
Can messages be sent manually?

### ISSUE THREAD

**Issue by DavidAdamsBluecity** [rsmp-nordic/rsmp_core#103]
Sorry if this is too similar to the [issue](https://github.com/rsmp-nordic/rsmp/issues/42) I made in the RSMP ruby gem repo, but this might be more related to the core specification itself. Once the site and supervisor are established, it seems as though all messages are expected to be sent by the equipment itself. Is this correct? Or can the user send a message through this established connection somehow, even without equipment connected?

**Comment by otterdahl** [comment]
> Once the site and supervisor are established, it seems as though all messages are expected to be sent by the equipment itself. Is this correct?

Not really. Several types of messages can be sent by the supervision system. E.g. Alarm acknowledge, Alarm suspend/resume, StatusRequest, StatusSubscription, CommandRequest, Watchdog, and so on.

> Or can the user send a message through this established connection somehow, even without equipment connected?

It depends on how use define `user` and how to you establish connection without connected equipment. I'm a bit confused.

**Comment by otterdahl** [comment]
I suppose you could send a Watchdog message manually. You should receive a MessageAck as a response.

**Comment by DavidAdamsBluecity** [comment]
Thanks for the response. The impression I get is that the site and supervisor are more or less autonomous. They do what they're supposed to do after receiving the messages they're listening for. I guess my confusion is where these various types of messages are meant to come from.

From the implementation workflows, it seems that the messages are expected to be initiated by TLC equipment or a simulator software rather than manual user input. Technically the latter would be possible, but it doesn't seem to be a specific component of this protocol. Have I understood that correctly?

**Comment by otterdahl** [comment]
Yes, I think you're right.

The  RSMP simulator for windows were made to be an interactive simulator were the user could do things manually.

The `rsmp_validator` and `rsmp` ruby gem were focused on being able to automate validation of RSMP implementations by running test cases with rspec. I think they are lacking an interactive mode. However, it would be a great feature.

**Comment by DavidAdamsBluecity** [comment]
Then if there were a piece of equipment, say a small computer, directly connected to a TLC via RSMP connection, what would be the expected method for it to begin asynchronous message exchange after establishing itself as a site according to this protocol?

I'm modifying the ruby gem API to allow for a message to be sent before the indefinite wait for the asynchronous task's completion begins, but I'm having trouble getting the recipient to acknowledge it. It seems like sending a message from one box to another should be a simpler task than I'm making it out to be. Is there some simpler method I'm overlooking?

Thanks.

**Comment by otterdahl** [comment]
> Then if there were a piece of equipment, say a small computer, directly connected to a TLC via RSMP connection, what would be the expected method for it to begin asynchronous message exchange after establishing itself as a site according to this protocol?

If you connect a piece of equipment directly to a TLC, my recommendation is that the equipment acts as a supervisor (and not a site). I know that RSMP defines both communication supervison-site as well as [site-site](https://rsmp-nordic.org/rsmp_specifications/core/3.2/applicability/transport_of_data.html#communication-establishment-between-sites), however site-site was specifically added in order to support [coordnation between TLC's](https://rsmp-nordic.org/rsmp_specifications/rsmp_sxl_traffic_lights/1.1/coordination.html#coordination-between-traffic-light-controllers) and I don't know how well TLC's actually supports it when used for other purposes. On the other hand, supervision-site is well tested.

When using supervisor-site, the supervisor needs to listen to a port (typically 12111). The site (TLC) is expected  to connect to the supervisor (in this case the equipment).

Regardless of using supervision-site or site-site communication, the [section on communication establishment](https://rsmp-nordic.org/rsmp_specifications/core/3.2/applicability/transport_of_data.html?highlight=asyn#communication-establishment-between-sites-and-supervision-system) defines when asynchronous message exchange can begin. Basically after the [version messages](https://rsmp-nordic.org/rsmp_specifications/core/3.2/applicability/basic_structure.html#rsmp-sxl-version) and the first [watchdog messages](https://rsmp-nordic.org/rsmp_specifications/core/3.2/applicability/basic_structure.html#watchdog) has been exchanged.

> I'm modifying the ruby gem API to allow for a message to be sent before the indefinite wait for the asynchronous task's completion begins, but I'm having trouble getting the recipient to acknowledge it. It seems like sending a message from one box to another should be a simpler task than I'm making it out to be. Is there some simpler method I'm overlooking?

Sorry, I don't know the ruby gem well enough. Perhaps @emiltin can answer when he gets back.

**Comment by otterdahl** [comment]
@DavidAdamsBluecity Is this issue still relevant? Let me know if this is still an issue for you or if we can close it.

**Comment by DavidAdamsBluecity** [comment]
Definitely resolved for me. Thanks!
