### ISSUE TITLE
Consider the option to be able to select if the site or supervision system acts as server/client

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_core#147]
We've received feedback that it might be good to be able to choose if the site or supervision system acts as a socket server or client.

RSMP currently specifies the supervision system to implement a socket server and listen for incoming connections. For some road authorities it is prefered that each road equipment does this instead.

If this option is added, the section 4.3 "Transport of data" needs to updated to better separate the TCP server/client and the RSMP communication parts.

**Comment by emiltin** [comment]
I understand the consideration, but it's rather big change I think.

How would it affect handshake, delivery of buffered messages, etc?
What happens if both site and supervisor are configured as a lister, or a client? 

Side note: With MQTT, the broker is always the listener, so both sites and supervisors could initiate connections to the broker.

**Comment by otterdahl** [comment]
This option doesn't affect any RSMP messages at all. The message flow remain unaffected. The only change is who initiates the connection and who listens for incomming connections.

From an RSMP standpoint the impact is small. But it matters to IT-management of the road authority. If affects how to manage the firewalls, keep track of IP adresses to each equipment and so on.

The RSMP simulators can already be configured to work this way. But the configuration option was undocumented until now.

**Comment by emiltin** [comment]
pro:
- the central system connecting to devices is perhaps more traditional, and might make it easier to setup firewalls, etc.
- if a lot of equipment tries to connect at the same time, it can create bottlenecks at the central server
- equipment can keep trying to connect
- you need more configuration on the device, because it needs to know where to connect to

con:
- if equipment is not using static ips, it's easier to have the site connect to the server.
- rsmp 4 will probably be based on mqtt, where all devices connect to a central broker, which is similar to how we currently do it with rsmp 3.

Web interfaces we have today is an example of conecting from the server side to the device. If you can then configure where the site should connect to, you will not need to go out in the field to update the config.

Things get a bit more complicated if we make it an option: documentation, debugging, etc. Also out tools would need to implement it.

**Comment by emiltin** [comment]
Can we get more info from the French partners about what their need is?

**Comment by marcgarba** [comment]
As you very well listed in the pro/con list items,
in case of dialog between "supervision <-> equipment",
depending of the type of network infrastructure (or operator's choices, or for historical reason with network configuration designed for that),
sometimes an equipment must be able to communicate as a TCP server, or as a TCP client.

So it would be interesting not to limit the specifications to a single direction mode usable for the case "supervision <-> equipment",
but to totally well separate protocol messaging RSMP from the low-level TCP link.

Then, everyone would be able to use the TCP direction mode they prefer or find most suitable !

For info, in France on all the "private" IP networks (copper, fiber), for equipements used in 'TCP' mode, they are all TCP server, and the supervision acts as a client TCP.
In the case of cellular network 3G/4G (especially if the dynamic IP is private), and if it's not used as VPN, the equipements would preferably be TCP client.

As you can see, both are interesting, depending on many situations....

I think only the 4.3.8 chapter needs to be extended concerning the client/server TCP sockets with possible 2 directions modes . And keep the current mode (equipment=client / supervision=server) as "default" mode used in RSMP.
(not all tools and supervision tools systems will be required to support both modes)

**Comment by emiltin** [comment]
OK, it seems if should not affect the RSMP messaging or connection sequence. But:
- you need an additional configuration in supervisors and systems.
- supervisor system might have to act as both tcp client and tcp supervisor in case devices are configured differently
- the RSMP Simulator and RSMP Validator would have to support it

We could try to implement it in our test tools first to verify that it has no unintended consequences.

**Comment by marcgarba** [comment]
To be confirmed by @otterdahl , but if I remember correctly, the Windows simulators RSMPG1 and RSMPG2 both can already be used with TCP server/client mode inverted.

**Comment by otterdahl** [comment]
> To be confirmed by @otterdahl , but if I remember correctly, the Windows simulators RSMPG1 and RSMPG2 both can already be used with TCP server/client mode inverted.

Correct

**Comment by emiltin** [comment]
If a site is configured to connect to multiple supervisor, should you be able to act as a client towards some supervisor, and as a server towards others?

**Comment by marcgarba** [comment]
If all supervisors are on the same network, I don't think it could happen.
But in theory, you could have one supervisor on a private network (equipment as TCP server), on another via a cellular modem-router for example  (supervisor as TCP server)...

**Comment by otterdahl** [comment]
I've opened a PR here: https://github.com/rsmp-nordic/rsmp_core/pull/199
Only site-supervision connection is covered so far.
