### ISSUE TITLE
Status subscribe, and possible link between updateRate and sendOnChange (when combined)

### ISSUE THREAD

**Issue by marcgarba** [rsmp-nordic/rsmp_core#150]
The RSMP specifications don't really describe what to do if you subscribe to both updateRate and sendOnChange.
If a change occurs, does the period restart or not?
It might be interesting not to have an independent period flow, to avoid too many unnecessary messages: if a change occurs, and a statusUpdate has been sent, with an independent period, a few moments later a new statusUpdate could be sent with the same value...

It seems that simulators currently work in this case in a totally independent way between the two.

Are these two possibilities acceptable?

**Comment by otterdahl** [comment]
> The RSMP specifications don't really describe what to do if you subscribe to both updateRate and sendOnChange. If a change occurs, does the period restart or not? It might be interesting not to have an independent period flow, to avoid too many unnecessary messages: if a change occurs, and a statusUpdate has been sent, with an independent period, a few moments later a new statusUpdate could be sent with the same value...

The intent of the specification is that the updateRate timer works independently from sendOnChange and that the period does not restart on if the value changes.

To possibility use both updateRate and sendOnChange=true was added to specification due to some supervision system sometimes looses track of the latest value since some values very rarely changes and almost never gets sent/updated when using only sendOnChange=true.

> Are these two possibilities acceptable?

It is an interesting propsition. Maybe it is a better solution to reset the updateRate timer on change if sendOnChange=true is used. That would reduce unnecessary messages to be sent. I don't think this change/clarification breaks any existing implementations.

Perhaps we can include this clarification in the next release.
Your thoughts  @emiltin ?

**Comment by emiltin** [comment]
This is a bit similar to the discussion on watchdog. They also have an interval, but if somethings else is send, you could skip them, as you know the connection is up.

For status. message, I think it would make sense to consider updateRate as a max interval between updates. If sendOnChange is also on, you get a status whenever the status change, and when ever updateRate has passed. Whenever you send a status, you reset the updateRate timer.

I believe this is what you also suggested @marcgarba.

**Comment by marcgarba** [comment]
For the watchdog, as there is only "one" message per minute (by default), this doesn't represent much.
But with subscriptions, if you have lots of (changing) signals and a short set period, there can be far fewer messages exchanged (if the timer is restarted)! And therefore much more interesting.

We could at least suggest in the specifications that it could be done this way!

**Comment by otterdahl** [comment]
We think this is a good idea to add in 3.2.2. PR is created here: https://github.com/rsmp-nordic/rsmp_core/pull/157

**Comment by marcgarba** [comment]
Good news !
Thanks.

**Comment by otterdahl** [comment]
The PR has been merged so I think we can close this issue.
