### ISSUE TITLE
Are objects and components the same things?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_core#177]
If objects and components are the same things, then I suggest we pick one of the terms and use that everywhere, to avoid confusion.

The attribute "cId" is used to refer to component id. Changing this would be a diffucult braking change, so if we want to change something, weI suggest we rename object to component.

**Comment by emiltin** [comment]
The current core doc refers to following the Datex II meta-model. Is this still relevant, and what does it imply?

**Comment by otterdahl** [comment]
> If objects and components are the same things, then I suggest we pick one of the terms and use that everywhere, to avoid confusion.
> 
> The attribute "cId" is used to refer to component id. Changing this would be a diffucult braking change, so if we want to change something, weI suggest we rename object to component.

From a protocol point of view, the are the same thing. The choice of terminology was used in order to better fit with other STA-specific documents. I'm in favor of changing this in the future

> The current core doc refers to following the Datex II meta-model. Is this still relevant, and what does it imply?

This was written a long time ago. I'm not an expert of Datex II but I believe this text is outdated. But I think that nowadays Datex II contains traffic signal related information as well, so perhaps Datex II is a competing standard nowadays. Sometimes Datex II is criticized for low performance (maybe because it uses XML?) , making it unsuitable for some use cases, but I'm not sure about it's latest developments.

**Comment by emiltin** [comment]
OK then let's device on object or component and be consistent: #186
And let's remove reference to Datex II: #185

**Comment by emiltin** [comment]
closing in favour of #186
