### ISSUE TITLE
CommandResponse and acknowledgements

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_core#58]
Is it valid for a site to respond to a CommandRequest into multiple CommandResponse messages?

Must the CommandResponse be either acknowledged or notAcknowledged before the first response is sent?

**Comment by otterdahl** [comment]
> Is it valid for a site to respond to a CommandRequest into multiple CommandResponse messages?

Well yes. I think it is possible since we can send multiple commands in a single CommandsRequest. A CommandReponse may also contain multiple command responses. A smart system/road side equipment has the opportunity to bundle several commands like this in order to increase performance, but it reality it seldomly happens.

The CommandResponse is supposed to be sent when the the [value of the command is `set` in the equipment](https://rsmp-nordic.github.io/rsmp_core/applicability/sxl.html#write-operation). If this happens at different times for different commands (depending on the equipment) - I think it is possible - at least it is not explicitly disallowed - but this seldomly happens in reality. 

The CommandResponse needs to be either acknowledged or notAcknowledged before the first response is sent.
See [4.4.6. Message acknowledgement](https://rsmp-nordic.github.io/rsmp_core/applicability/basic_structure.html?highlight=messageack#message-acknowledgement): `Message acknowledgement is sent as an initial answer to all other messages.`.

**Comment by emiltin** [comment]
ok

**Comment by emiltin** [comment]
Partial status updates are mentioned in the spec, but not partial command requests? I think we should describe whether it's allowed.

**Comment by emiltin** [comment]
Can a command response also contain responses to multiple commands?

**Comment by otterdahl** [comment]
Yes. A CommandReponse may contain multiple command responses.

**Comment by emiltin** [comment]
let's check if it's clear in the spec

**Comment by otterdahl** [comment]
I've updated the spec. See 86e3ad9e58a18026b4c27e4443cf69049c2bcf9e
