### ISSUE TITLE
dynniq ec-2 uses "SXL" : "1.0.7.C.001"

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_core#59]
Is a site allowed to send custom sxl versions? Or should it be limited to official sxl version?
The schema currently requires "^[0-9]{1,2}\\.[0-9]{1,2}(\\.[0-9]{1,2})?", ie. it must start with e.g 1.2 or 1.2.3 , and after that can contain any additional characters

**Comment by otterdahl** [comment]
This was discussed in https://github.com/rsmp-nordic/rsmp_core/issues/39

The extra "C.001" was needed for our supervision system due to the EC-2 controller disconnecting immediately upon receiving a status or command it didn't support. The extra "C.001" represented a reduced set of statuses and commands that their specific TLC supported. Since RSMP 3.1.3 and later, the spec has been clarified not to disconnect upon receiving a unknown status or command. It must instead send MessageNotAck and continue the connection.

**Comment by emiltin** [comment]
closing in favour of #39
