### ISSUE TITLE
should subscriptions persists across restarts / power outages?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_core#74]

**Comment by otterdahl** [comment]
I don't think it is necessary to require that subscriptions should persist across restarts or power outages of the equipment. Once the equipment powers up, the communication should be reestablished and the supervision typically sends new subscription requests. If the equipment lacks power then it won't buffer anything anyway.

Communication disruption is a different story where there is a point to require it since the equipment typically can continue to function as normal, but without connection to supervisor. Cellular networks can be flaky and we don't want to loose e.g. traffic counting data because intermittent communication issues.
